name: VArenas
main: net.vectorgaming.varenas.VArenas
version: 0.1
author: Kenny Williams
website: http://vectorgaming.net
description: Player versus player arena manager

depend: [ZoneCore, ZoneWorld, VCore, VChat]
softdepend: [WorldInventories,MobArena,ArenaKits]